<?php

namespace Facebes\WeightControlBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DataWeightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataWeightRepository extends EntityRepository
{
}