<?php

namespace Facebes\WeightControlBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WeightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeightRepository extends EntityRepository
{
}